<?php
/**
 * @var $block \Genaker\EmojiGame\Block\EmojiGame
 */

 $reactGameUrlJS = $block->getViewFileUrl('Genaker_EmojiGame::game.compiled.js');
 $reactGameUrlCSS = $block->getViewFileUrl('Genaker_EmojiGame::game.css');
?>
<div id="game">

</div>

<script src="<?=$reactGameUrlJS?>"> </script>
<link rel="stylesheet" href="<?= $reactGameUrlCSS?>"/>
<script>

ReactDOM.render( /*#__PURE__*/React.createElement(React.StrictMode, null, /*#__PURE__*/React.createElement(App, null)), document.getElementById('game'));
</script>